export const environment = {
  production: true,
  baseUrl: 'https://films-db-2021.herokuapp.com/api',
  filmsImageUrl: 'https://films-db-2021.herokuapp.com/api/upload/films',
  usersImageUrl: 'https://films-db-2021.herokuapp.com/api/upload/users',
  avatars: [
    'assets/avatars/1.png',
    'assets/avatars/2.png',
    'assets/avatars/3.png',
    'assets/avatars/4.png',
    'assets/avatars/5.png',
    'assets/avatars/6.png',
    'assets/avatars/7.png',
    'assets/avatars/8.png',
    'assets/avatars/9.png',
    'assets/avatars/10.png',
    'assets/avatars/11.png',
    'assets/avatars/12.png',
    'assets/avatars/13.png',
    'assets/avatars/14.png',
    'assets/avatars/15.png',
    'assets/avatars/16.png',
    'assets/avatars/17.png',
    'assets/avatars/18.png',
    'assets/avatars/19.png',
    'assets/avatars/20.png',
    'assets/avatars/account.png',
  ]
};
